kind: Job
apiVersion: batch/v1
metadata:
  name: j1
spec:
  template:
    spec:
      containers:
      - name: j1
        image: docker/whalesay
        command: ["cowsay","Test Title"]    
      restartPolicy: Never
  activeDeadlineSeconds: 60 
  backoffLimit: 4

OR

kubectl run my-job --image=docker/whalesay --restart=OnFailure -o yaml --dry-run -- cowsay > job.yaml
